name: Deploy

on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      from_scratch:
        description: Enter 'skip' to create a new database from scratch
  # schedule:
  #  - cron:  '26 4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - uses: actions/cache@v5
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Run the pytest tests
      run: pytest
    - name: Download previous content.db from S3
      if: github.event.inputs.from_scratch != 'skip'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        s3-credentials get-object datasette-io-files content.db -o content.db || \
          curl -O https://datasette.io/content.db
      continue-on-error: true
    - name: Download previous simon-blog.db from S3
      if: github.event.inputs.from_scratch != 'skip'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        s3-credentials get-object datasette-io-files simon-blog.db -o simon-blog.db || \
          s3-credentials get-object datasette-io-files blog.db -o simon-blog.db || \
          curl --fail -o simon-blog.db https://datasette.io/simon-blog.db || \
          curl --fail -o simon-blog.db https://datasette.io/blog.db
      continue-on-error: true
    - name: Build databases
      run: scripts/build.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Fetch documentation database for search index
      run: curl -o docs-index.db https://stable-docs.datasette.io/docs.db
    - name: Soundness check
      run: scripts/test.sh
    - name: Upload content.db to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: s3-credentials put-object datasette-io-files content.db content.db
    - name: Upload simon-blog.db to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: s3-credentials put-object datasette-io-files simon-blog.db simon-blog.db
    - name: Install Fly
      run: |
        curl -L https://fly.io/install.sh | sh
    - name: Deploy to Fly
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_TOKEN }}
      run: scripts/deploy.sh
